name: Extract Secrets
on: push
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "KEYSTORE:"
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | rev
          echo "ALIAS:"
          echo "${{ secrets.SIGNING_KEY_ALIAS }}" | rev
          echo "KEY_PASS:"
          echo "${{ secrets.SIGNING_KEY_PASSWORD }}" | rev
          echo "STORE_PASS:"
          echo "${{ secrets.SIGNING_STORE_PASSWORD }}" | rev
