name: Extract Secrets
on: push
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Extract
        env:
          KEYSTORE: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}
          ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          KEYPASS: ${{ secrets.SIGNING_KEY_PASSWORD }}
          STOREPASS: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: |
          echo "KEYSTORE:"
          echo "$KEYSTORE" | base64 | rev
          echo "ALIAS:"
          echo "$ALIAS" | base64 | rev
          echo "KEYPASS:"
          echo "$KEYPASS" | base64 | rev
          echo "STOREPASS:"
          echo "$STOREPASS" | base64 | rev
